version = 1
nebula_name = 'git-branching'

[phases]
[phases.branch-manager]
bead_id = 'quasar-20u'
status = 'in_progress'
created_at = 2026-02-18T10:54:52.863031-05:00
updated_at = 2026-02-18T10:54:54.051161-05:00

[phases.nebula-branch-lifecycle]
bead_id = 'quasar-dne'
status = 'created'
created_at = 2026-02-18T10:54:53.242269-05:00
updated_at = 2026-02-18T10:54:53.242269-05:00

[phases.readable-cycle-commits]
bead_id = 'quasar-04z'
status = 'created'
created_at = 2026-02-18T10:54:53.602655-05:00
updated_at = 2026-02-18T10:54:53.602655-05:00

[phases.readable-phase-commits]
bead_id = 'quasar-61p'
status = 'created'
created_at = 2026-02-18T10:54:53.971285-05:00
updated_at = 2026-02-18T10:54:53.971285-05:00
