version = 1
nebula_name = 'commit-tracking'

[phases]
[phases.checkpoint-range-diff]
bead_id = 'quasar-k2e'
status = 'created'
created_at = 2026-02-18T22:25:34.081744-05:00
updated_at = 2026-02-18T22:25:34.081744-05:00

[phases.cycle-final-sha]
bead_id = 'quasar-l90'
status = 'in_progress'
created_at = 2026-02-18T22:25:34.480033-05:00
updated_at = 2026-02-18T22:25:36.001193-05:00

[phases.range-diff]
bead_id = 'quasar-85a'
status = 'created'
created_at = 2026-02-18T22:25:34.843089-05:00
updated_at = 2026-02-18T22:25:34.843089-05:00

[phases.revert-to-cycle]
bead_id = 'quasar-5gy'
status = 'created'
created_at = 2026-02-18T22:25:35.207046-05:00
updated_at = 2026-02-18T22:25:35.207046-05:00

[phases.task-result-shas]
bead_id = 'quasar-2ov'
status = 'created'
created_at = 2026-02-18T22:25:35.598428-05:00
updated_at = 2026-02-18T22:25:35.598428-05:00
