version = 1
nebula_name = 'Test Coverage Improvements'

[phases]
[phases.beads-exec]
bead_id = 'quasar-rq3'
status = 'in_progress'
created_at = 2026-02-17T14:05:03.479221-05:00
updated_at = 2026-02-17T14:05:04.839939-05:00

[phases.claude-exec]
bead_id = 'quasar-h92'
status = 'in_progress'
created_at = 2026-02-17T14:05:03.857905-05:00
updated_at = 2026-02-17T14:05:04.834109-05:00

[phases.loop-core]
bead_id = 'quasar-2qh'
status = 'created'
created_at = 2026-02-17T14:05:04.187147-05:00
updated_at = 2026-02-17T14:05:04.187147-05:00

[phases.ui-printer]
bead_id = 'quasar-c5e'
status = 'in_progress'
created_at = 2026-02-17T14:05:04.563044-05:00
updated_at = 2026-02-17T14:05:04.838192-05:00
