version = 1
nebula_name = 'scanning-and-gate-fixes'

[phases]
[phases.auto-enable-contract-board]
bead_id = 'quasar-vpfc'
status = 'failed'
created_at = 2026-02-24T12:03:40.443703-05:00
updated_at = 2026-02-24T12:06:54.793261-05:00

[phases.gate-prompt-overflow]
bead_id = 'quasar-uhds'
status = 'failed'
created_at = 2026-02-24T12:03:39.042584-05:00
updated_at = 2026-02-24T12:06:54.725347-05:00

[phases.graph-gate-color-fix]
bead_id = 'quasar-ozjq'
status = 'failed'
created_at = 2026-02-24T12:03:39.739132-05:00
updated_at = 2026-02-24T12:06:53.852054-05:00

[phases.graph-legend-and-gate-status]
bead_id = 'quasar-2qg2'
status = 'failed'
created_at = 2026-02-24T12:03:41.14694-05:00
updated_at = 2026-02-24T12:06:46.471811-05:00

[phases.homepage-layout-squished]
bead_id = 'quasar-alqk'
status = 'failed'
created_at = 2026-02-24T12:03:42.530822-05:00
updated_at = 2026-02-24T12:06:51.098679-05:00

[phases.phase-timer-cumulative]
bead_id = 'quasar-05os'
status = 'failed'
created_at = 2026-02-24T12:03:41.821586-05:00
updated_at = 2026-02-24T12:06:47.995258-05:00

[phases.remove-scanning-column]
bead_id = 'quasar-h2l0'
status = 'failed'
created_at = 2026-02-24T12:03:37.617952-05:00
updated_at = 2026-02-24T12:06:49.113923-05:00

[phases.scanning-toast]
bead_id = 'quasar-opk6'
status = 'created'
created_at = 2026-02-24T12:03:38.326562-05:00
updated_at = 2026-02-24T12:03:38.326562-05:00
