version = 1
nebula_name = 'TUI Fix-up & Polish'

[phases]
[phases.diff-nav-bugs]
bead_id = 'quasar-uzr'
status = 'created'
created_at = 2026-02-18T09:32:44.589955-05:00
updated_at = 2026-02-18T09:32:44.589955-05:00

[phases.esc-escape-hatch]
bead_id = 'quasar-80r'
status = 'created'
created_at = 2026-02-18T09:32:44.998444-05:00
updated_at = 2026-02-18T09:32:44.998444-05:00

[phases.header-consistency]
bead_id = 'quasar-jw6'
status = 'in_progress'
created_at = 2026-02-18T09:32:45.377295-05:00
updated_at = 2026-02-18T09:32:46.078882-05:00

[phases.phase-status-distinction]
bead_id = 'quasar-2ba'
status = 'created'
created_at = 2026-02-18T09:32:45.798334-05:00
updated_at = 2026-02-18T09:32:45.798334-05:00
