version = 1
nebula_name = 'auto-decomposition'

[phases]
[phases.dag-insertion]
bead_id = 'quasar-30h1'
status = 'created'
created_at = 2026-02-28T23:19:20.342678-05:00
updated_at = 2026-02-28T23:19:20.342678-05:00

[phases.decomposition-architect]
bead_id = 'quasar-7z00'
status = 'created'
created_at = 2026-02-28T23:19:19.525154-05:00
updated_at = 2026-02-28T23:19:19.525154-05:00

[phases.observability]
bead_id = 'quasar-bcsk'
status = 'created'
created_at = 2026-02-28T23:19:21.85957-05:00
updated_at = 2026-02-28T23:19:21.85957-05:00

[phases.struggle-detection]
bead_id = 'quasar-080u'
status = 'in_progress'
created_at = 2026-02-28T23:19:18.783866-05:00
updated_at = 2026-02-28T23:19:21.929379-05:00

[phases.worker-integration]
bead_id = 'quasar-iyyo'
status = 'created'
created_at = 2026-02-28T23:19:21.072232-05:00
updated_at = 2026-02-28T23:19:21.072232-05:00
