version = 1
nebula_name = 'cockpit-ui-polish'

[phases]
[phases.deprecate-beads-view]
bead_id = 'quasar-1bgm'
status = 'in_progress'
created_at = 2026-02-24T10:55:46.905863-05:00
updated_at = 2026-02-24T10:55:48.657417-05:00

[phases.logo-top-not-side]
bead_id = 'quasar-k6g8'
status = 'created'
created_at = 2026-02-24T10:55:48.355176-05:00
updated_at = 2026-02-24T10:55:48.355176-05:00

[phases.table-mode-toggle-hint]
bead_id = 'quasar-7q4p'
status = 'created'
created_at = 2026-02-24T10:55:47.600094-05:00
updated_at = 2026-02-24T10:55:47.600094-05:00
