version = 1
nebula_name = 'Reviewer Memory'

[phases]
[phases.finding-lifecycle]
bead_id = 'quasar-trjs'
status = 'skipped'
created_at = 2026-02-28T20:25:18.152701-05:00
updated_at = 2026-02-28T22:55:26.25873-05:00

[phases.finding-serialization]
bead_id = 'quasar-0al5'
status = 'in_progress'
created_at = 2026-02-28T20:25:15.734321-05:00
updated_at = 2026-02-28T22:55:26.327879-05:00

[phases.prompt-injection]
bead_id = 'quasar-3pz7'
status = 'created'
created_at = 2026-02-28T20:25:16.546975-05:00
updated_at = 2026-02-28T22:55:26.258103-05:00

[phases.verification-parsing]
bead_id = 'quasar-1e81'
status = 'created'
created_at = 2026-02-28T20:25:17.403684-05:00
updated_at = 2026-02-28T22:55:26.258497-05:00
