version = 1
nebula_name = 'beads-dag-fix'

[phases]
[phases.fix-bead-wall-of-text]
bead_id = 'quasar-ijp'
status = 'in_progress'
created_at = 2026-02-18T14:40:51.667428-05:00
updated_at = 2026-02-18T14:40:52.032173-05:00
