version = 1
nebula_name = 'diffraction'

[phases]
[phases.contract-poller]
bead_id = 'quasar-3tjq'
status = 'in_progress'
created_at = 2026-02-24T09:38:50.053004-05:00
updated_at = 2026-02-24T09:38:52.531417-05:00

[phases.poller-wiring]
bead_id = 'quasar-r9d1'
status = 'created'
created_at = 2026-02-24T09:38:52.244001-05:00
updated_at = 2026-02-24T09:38:52.244001-05:00

[phases.soft-dag]
bead_id = 'quasar-gtqg'
status = 'created'
created_at = 2026-02-24T09:38:51.471329-05:00
updated_at = 2026-02-24T09:38:51.471329-05:00

[phases.wave-scanner]
bead_id = 'quasar-my9s'
status = 'created'
created_at = 2026-02-24T09:38:50.775997-05:00
updated_at = 2026-02-24T09:38:50.775997-05:00
