version = 1
nebula_name = 'TUI Bug Fixes'

[phases]
[phases.architect-wiring]
bead_id = 'quasar-ro2'
status = 'in_progress'
created_at = 2026-02-17T11:52:42.480252-05:00
updated_at = 2026-02-17T11:53:39.7865-05:00

[phases.beads-plan-views]
bead_id = 'quasar-tmw'
status = 'created'
created_at = 2026-02-17T11:52:42.856203-05:00
updated_at = 2026-02-17T11:53:39.711403-05:00

[phases.detail-refresh]
bead_id = 'quasar-t36'
status = 'in_progress'
created_at = 2026-02-17T11:52:43.187658-05:00
updated_at = 2026-02-17T11:53:39.782976-05:00

[phases.detail-text-wrap]
bead_id = 'quasar-ctz'
status = 'created'
created_at = 2026-02-17T11:52:43.539996-05:00
updated_at = 2026-02-17T11:53:39.712069-05:00

[phases.diff-state-fix]
bead_id = 'quasar-2cw'
status = 'created'
created_at = 2026-02-17T11:52:43.881959-05:00
updated_at = 2026-02-17T11:53:39.712302-05:00
