version = 1
nebula_name = 'adaptive-routing'

[phases]
[phases.cli-override]
bead_id = 'quasar-0qj0'
status = 'created'
created_at = 2026-02-28T20:04:56.20904-05:00
updated_at = 2026-02-28T20:04:56.20904-05:00

[phases.complexity-scorer]
bead_id = 'quasar-iyiv'
status = 'in_progress'
created_at = 2026-02-28T20:04:52.976185-05:00
updated_at = 2026-02-28T20:04:56.488851-05:00

[phases.model-tiers]
bead_id = 'quasar-mo9j'
status = 'in_progress'
created_at = 2026-02-28T20:04:53.807243-05:00
updated_at = 2026-02-28T20:04:56.487466-05:00

[phases.resolve-integration]
bead_id = 'quasar-eirj'
status = 'created'
created_at = 2026-02-28T20:04:54.712994-05:00
updated_at = 2026-02-28T20:04:54.712994-05:00

[phases.telemetry]
bead_id = 'quasar-edgd'
status = 'created'
created_at = 2026-02-28T20:04:55.482685-05:00
updated_at = 2026-02-28T20:04:55.482685-05:00
